const KEY='grocery-assistant-v1';
const defaultData={items:[],lists:[{id:'main',name:'Weekly Groceries',icon:'🛒',color:'green'}],meals:[],settings:{theme:'system',currency:'USD',sound:true,hideBought:false,largeText:false}};
let data=load();let editingId=null;let wakeLock=null;
const $=id=>document.getElementById(id);
function load(){try{return {...defaultData,...JSON.parse(localStorage.getItem(KEY)||'{}') ,settings:{...defaultData.settings,...(JSON.parse(localStorage.getItem(KEY)||'{}').settings||{})}}}catch{return structuredClone(defaultData)}}
function save(){localStorage.setItem(KEY,JSON.stringify(data));render()}
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function money(n){return new Intl.NumberFormat(undefined,{style:'currency',currency:data.settings.currency||'USD'}).format(Number(n)||0)}
function parseQuick(text){let m=text.trim().match(/^(\d+(?:\.\d+)?)\s+(.+)$/);let qty=m?Number(m[1]):1;let name=m?m[2]:text.trim();let units=['gallon','gallons','lb','lbs','oz','kg','g','dozen','bunch','pack','packs','liter','liters'];let unit='';let u=name.match(new RegExp('^('+units.join('|')+')\\s+(.+)$','i'));if(u){unit=u[1].toLowerCase();name=u[2]}return {name,qty,unit}}
function guessCategory(name){let n=name.toLowerCase();if(/apple|banana|lettuce|tomato|potato|onion|carrot|fruit|vegetable|berry|avocado/.test(n))return'Produce';if(/milk|cheese|yogurt|butter|cream|egg/.test(n))return'Dairy';if(/chicken|beef|pork|turkey|meat|sausage|fish/.test(n))return'Meat';if(/bread|bun|bagel|tortilla|bakery/.test(n))return'Bakery';if(/frozen|ice cream/.test(n))return'Frozen';if(/water|soda|juice|coffee|tea|drink/.test(n))return'Beverages';if(/soap|paper|detergent|cleaner|trash|towel/.test(n))return'Household';if(/shampoo|toothpaste|deodorant/.test(n))return'Personal Care';if(/dog|cat|pet|litter/.test(n))return'Pet Supplies';return'Pantry'}
function addItem(raw){let p=parseQuick(raw);if(!p.name)return;data.items.push({id:uid(),name:p.name,qty:p.qty,unit:p.unit,category:guessCategory(p.name),price:'',brand:'',notes:'',favorite:false,bought:false,created:Date.now()});save();toast('Added '+p.name)}
function openItem(id=null){editingId=id;let x=data.items.find(i=>i.id===id);$('dialogTitle').textContent=id?'Edit item':'Add item';$('itemName').value=x?.name||'';$('itemQty').value=x?.qty||1;$('itemUnit').value=x?.unit||'';$('itemCategory').value=x?.category||'Pantry';$('itemPrice').value=x?.price??'';$('itemBrand').value=x?.brand||'';$('itemNotes').value=x?.notes||'';$('itemFavorite').checked=!!x?.favorite;$('itemDialog').showModal();setTimeout(()=>$('itemName').focus(),50)}
function closeDialog(){$('itemDialog').close();editingId=null}
$('itemForm').addEventListener('submit',e=>{e.preventDefault();let item={id:editingId||uid(),name:$('itemName').value.trim(),qty:Number($('itemQty').value)||1,unit:$('itemUnit').value,category:$('itemCategory').value,price:$('itemPrice').value,brand:$('itemBrand').value.trim(),notes:$('itemNotes').value.trim(),favorite:$('itemFavorite').checked,bought:false,created:Date.now()};if(editingId){let old=data.items.find(i=>i.id===editingId);item.bought=old?.bought||false;data.items=data.items.map(i=>i.id===editingId?item:i)}else data.items.push(item);save();closeDialog();toast(editingId?'Item updated':'Item added')});
$('closeDialog').onclick=closeDialog;$('cancelDialog').onclick=closeDialog;
function toggle(id){let x=data.items.find(i=>i.id===id);if(!x)return;x.bought=!x.bought;if(x.bought&&data.settings.sound)beep();save();if(x.bought&&data.items.filter(i=>!i.bought).length===0&&data.items.length)toast('🎉 Nice! You are done!')}
function deleteItem(id){let x=data.items.find(i=>i.id===id);if(!x)return;data.items=data.items.filter(i=>i.id!==id);save();toast('Deleted '+x.name+' · tap Undo');$('toast').dataset.undo=JSON.stringify(x)}
let toastTimer;function toast(msg){clearTimeout(toastTimer);$('toast').textContent=msg;$('toast').classList.add('show');toastTimer=setTimeout(()=>{$('toast').classList.remove('show');$('toast').dataset.undo=''},2500)}
$('toast').onclick=()=>{let x=$('toast').dataset.undo;if(x){data.items.push(JSON.parse(x));save();toast('Restored')}};
function beep(){try{let a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.connect(g);g.connect(a.destination);o.frequency.value=660;g.gain.value=.04;o.start();o.stop(a.currentTime+.08)}catch{}}
function render(){renderList();renderShopping();renderMeals();renderLists();updateProgress();applySettings()}
function renderList(){let q=$('searchInput').value.toLowerCase().trim();let items=data.items.filter(i=>!q||[i.name,i.category,i.brand,i.notes].join(' ').toLowerCase().includes(q));if(data.settings.hideBought)items=items.filter(i=>!i.bought);let cats=[...new Set(items.map(i=>i.category))];$('listContainer').innerHTML=cats.length?cats.map(c=>`<section class="category"><div class="category-title">${catEmoji(c)} ${esc(c)}</div>${items.filter(i=>i.category===c).sort((a,b)=>a.bought-b.bought||b.favorite-a.favorite).map(itemHTML).join('')}</section>`).join(''):`<div class="empty"><div style="font-size:2rem">🛒</div><h3>${q?'No matches':'Your list is empty'}</h3><p>${q?'Try another search.':'Add your first grocery above!'}</p></div>`}
function itemHTML(i){let detail=[`${i.qty}${i.unit?' '+i.unit:''}`,i.brand,i.price!==''?money(i.price):'',i.notes].filter(Boolean).join(' · ');return `<article class="item ${i.bought?'done':''}" data-id="${i.id}"><input class="check" type="checkbox" ${i.bought?'checked':''} onchange="toggle('${i.id}')" aria-label="Mark ${esc(i.name)} bought"><div class="item-main" onclick="openItem('${i.id}')"><div class="item-name">${i.favorite?'⭐ ':''}${esc(i.name)}</div><div class="item-detail">${esc(detail)}</div></div><div class="item-actions"><button class="mini" onclick="openItem('${i.id}')" aria-label="Edit">✏️</button><button class="mini" onclick="deleteItem('${i.id}')" aria-label="Delete">🗑️</button></div></article>`}
function renderShopping(){let pending=data.items.filter(i=>!i.bought),done=data.items.filter(i=>i.bought);$('shoppingProgress').textContent=`${done.length} / ${data.items.length}`;$('shoppingList').innerHTML=[...pending,...done].map(i=>`<label class="shop-item ${i.bought?'done':''}"><input type="checkbox" ${i.bought?'checked':''} onchange="toggle('${i.id}')"><span>${i.favorite?'⭐ ':''}${esc(i.name)} <small>${i.qty}${i.unit?' '+i.unit:''}</small></span></label>`).join('')||'<div class="empty">Nothing to shop for yet.</div>'}
function renderMeals(){let meals=data.meals;if(!meals.length)$('mealGrid').innerHTML='<div class="empty" style="grid-column:1/-1">🍽️<h3>No meals planned</h3><p>Add meals and turn their ingredients into groceries.</p></div>';else $('mealGrid').innerHTML=meals.map(m=>`<div class="meal-card"><div>${m.icon||'🍽️'}</div><h3>${esc(m.name)}</h3><p>${esc(m.when||'Any time')} · ${m.ingredients?.length||0} ingredients</p><button class="small-btn" onclick="addIngredients('${m.id}')">Add ingredients</button></div>`).join('')}
function renderLists(){$('listsGrid').innerHTML=data.lists.map(l=>`<div class="list-card"><div style="font-size:1.8rem">${l.icon}</div><h3>${esc(l.name)}</h3><p>${data.items.length} items · ${data.items.filter(i=>i.bought).length} bought</p></div>`).join('')}
function updateProgress(){let total=data.items.length,bought=data.items.filter(i=>i.bought).length,p=total?Math.round(bought/total*100):0;$('progressText').textContent=`${bought} / ${total} items`;$('progressPercent').textContent=p+'%';$('progressBar').style.width=p+'%';$('totalText').textContent='Estimated total: '+money(data.items.reduce((s,i)=>s+(Number(i.price)||0)*(Number(i.qty)||1),0));$('remainingText').textContent=total?`${total-bought} left`:'Nothing added yet';let suggestions=data.items.filter(i=>i.favorite&&!i.bought).slice(0,8);$('suggestions').innerHTML=suggestions.map(i=>`<button class="chip" onclick="toggle('${i.id}')">⭐ ${esc(i.name)}</button>`).join('')}
function addIngredients(id){let m=data.meals.find(x=>x.id===id);m?.ingredients?.forEach(n=>addItem(n));toast('Ingredients added')}
$('quickAddBtn').onclick=()=>{addItem($('quickInput').value);$('quickInput').value='';$('quickInput').focus()};$('quickInput').addEventListener('keydown',e=>{if(e.key==='Enter'){$('quickAddBtn').click()}});$('searchInput').oninput=renderList;$('fab').onclick=()=>openItem();
$('themeBtn').onclick=()=>{data.settings.theme=data.settings.theme==='dark'?'light':'dark';save()};$('themeSelect').onchange=e=>{data.settings.theme=e.target.value;save()};$('currencySelect').onchange=e=>{data.settings.currency=e.target.value;save()};$('soundToggle').onchange=e=>{data.settings.sound=e.target.checked;save()};$('hideBoughtToggle').onchange=e=>{data.settings.hideBought=e.target.checked;save()};$('largeTextToggle').onchange=e=>{data.settings.largeText=e.target.checked;save()};
$('clearBtn').onclick=()=>{if(confirm('Delete all grocery data from this browser? This cannot be undone.')){localStorage.removeItem(KEY);data=structuredClone(defaultData);render();toast('All data cleared')}};
$('exportBtn').onclick=()=>{let blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='grocery-backup.json';a.click();URL.revokeObjectURL(a.href)};
$('newListBtn').onclick=()=>{let name=prompt('Name your new list');if(name?.trim()){data.lists.push({id:uid(),name:name.trim(),icon:'📋',color:'green'});save();toast('List created')}};
$('addMealBtn').onclick=()=>{let name=prompt('Meal name (example: Taco Night)');if(!name)return;let raw=prompt('Ingredients, separated by commas');let ingredients=(raw||'').split(',').map(x=>x.trim()).filter(Boolean);data.meals.push({id:uid(),name,when:'This week',ingredients,icon:'🍽️'});save();toast('Meal added')};
$('wakeBtn').onclick=async()=>{try{if(!wakeLock){wakeLock=await navigator.wakeLock?.request('screen');$('wakeBtn').textContent='Screen awake ✓'}else{await wakeLock.release();wakeLock=null;$('wakeBtn').textContent='Keep awake'}}catch{toast('Screen wake is not supported here')}};
function applySettings(){let s=data.settings;document.documentElement.dataset.theme=s.theme==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):s.theme;document.body.classList.toggle('large-text',!!s.largeText);$('themeSelect').value=s.theme;$('currencySelect').value=s.currency;$('soundToggle').checked=!!s.sound;$('hideBoughtToggle').checked=!!s.hideBought;$('largeTextToggle').checked=!!s.largeText}
function nav(view){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===view));document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('fab').style.display=view==='homeView'?'block':'none';scrollTo({top:0,behavior:'smooth'})}document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>nav(b.dataset.view));
function catEmoji(c){return({Produce:'🥦',Dairy:'🥛',Meat:'🥩',Bakery:'🥖',Frozen:'🧊',Pantry:'🥫',Beverages:'🥤',Household:'🧹','Personal Care':'🧴','Pet Supplies':'🐾',Other:'🛍️'})[c]||'🛍️'}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
const h=new Date().getHours();$('greeting').textContent=(h<12?'Good morning':h<17?'Good afternoon':'Good evening')+' 👋';
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
matchMedia('(prefers-color-scheme: dark)').addEventListener('change',()=>{if(data.settings.theme==='system')applySettings()});
render();
