(() => {
  'use strict';
  const KEY='grocery-assistant-v1';
  const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}};
  const write=d=>{localStorage.setItem(KEY,JSON.stringify(d));window.render?.()};
  const uid=()=>crypto.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2);
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const toast=m=>{const t=document.getElementById('toast');if(!t)return;t.textContent=m;t.classList.add('show');clearTimeout(window.__ft);window.__ft=setTimeout(()=>t.classList.remove('show'),2600)};
  const items=()=>{const d=read();return Array.isArray(d.items)?d.items:[]};
  const saveItems=a=>{const d=read();d.items=a;write(d)};

  function addToolbar(){
    const q=document.querySelector('.quick-add'); if(!q||document.getElementById('featureToolbar'))return;
    const bar=document.createElement('div');bar.id='featureToolbar';bar.className='feature-toolbar';
    bar.innerHTML='<button class="small-btn" id="bulkBtn">📋 Bulk add</button><button class="small-btn" id="clearBoughtBtn">🧹 Clear bought</button><button class="small-btn" id="sortBtn">↕️ Sort</button><button class="small-btn" id="moreBtn">✨ More</button>';
    q.insertAdjacentElement('afterend',bar);
    document.getElementById('clearBoughtBtn').onclick=()=>{const a=items().filter(i=>!i.bought);if(a.length===items().length){toast('No purchased items');return}saveItems(a);toast('Purchased items cleared')};
    document.getElementById('bulkBtn').onclick=bulkAdd;
    document.getElementById('sortBtn').onclick=sortMenu;
    document.getElementById('moreBtn').onclick=()=>openPanel('More grocery tools',moreTools());
  }
  function bulkAdd(){openPanel('Bulk add groceries','<p>Paste one item per line, or separate items with commas.</p><textarea id="bulkText" rows="8" placeholder="3 apples\n2 gallons milk\nCheddar cheese - large"></textarea><button class="primary" id="doBulk">Add all</button>');document.getElementById('doBulk').onclick=()=>{const raw=document.getElementById('bulkText').value;let a=items();raw.split(/[\n,]+/).map(x=>x.trim()).filter(Boolean).forEach(n=>{const m=n.match(/^(\d+(?:\.\d+)?)\s+(.+)$/);a.push({id:uid(),name:m?m[2]:n,qty:m?+m[1]:1,unit:'',category:'Pantry',price:'',brand:'',notes:'',favorite:false,bought:false,created:Date.now()})});saveItems(a);closePanel();toast('Groceries added')};}
  function sortMenu(){openPanel('Sort groceries','<button class="small-btn panel-wide" data-sort="name">A → Z</button><button class="small-btn panel-wide" data-sort="category">Category</button><button class="small-btn panel-wide" data-sort="price">Price</button><button class="small-btn panel-wide" data-sort="bought">Bought last</button><button class="small-btn panel-wide" data-sort="recent">Recently added</button>');document.querySelectorAll('[data-sort]').forEach(b=>b.onclick=()=>{const k=b.dataset.sort,a=items();a.sort((x,y)=>k==='name'?x.name.localeCompare(y.name):k==='category'?String(x.category).localeCompare(String(y.category)):k==='price'?(+y.price||0)-(+x.price||0):k==='bought'?x.bought-y.bought:(y.created||0)-(x.created||0));a.forEach((x,i)=>x.position=i);saveItems(a);closePanel();toast('List sorted')})}
  function moreTools(){return '<div class="tool-grid"><button class="small-btn" id="statsTool">📊 Statistics</button><button class="small-btn" id="historyTool">🗑️ History</button><button class="small-btn" id="storeTool">🏪 Stores</button><button class="small-btn" id="budgetTool">💰 Budget</button><button class="small-btn" id="receiptTool">🧾 Receipts</button><button class="small-btn" id="exportCsvTool">📄 CSV</button><button class="small-btn" id="exportTxtTool">📝 TXT</button><button class="small-btn" id="printTool">🖨️ Print</button><button class="small-btn" id="voiceTool">🎙️ Voice</button><button class="small-btn" id="barcodeTool">▦ Barcode</button><button class="small-btn" id="shareTool">🔗 Share</button><button class="small-btn" id="notifyTool">🔔 Reminders</button><button class="small-btn" id="importTool">📥 Import</button><button class="small-btn" id="customTool">🎨 Customize</button></div>'}

  function openPanel(title,body){closePanel();const d=document.createElement('dialog');d.id='featurePanel';d.innerHTML='<div class="feature-dialog"><div class="dialog-head"><h2>'+esc(title)+'</h2><button class="icon-btn" id="panelClose">✕</button></div><div class="panel-body">'+body+'</div></div>';document.body.appendChild(d);d.showModal();document.getElementById('panelClose').onclick=closePanel;wirePanel();}
  function closePanel(){document.getElementById('featurePanel')?.remove()}
  function wirePanel(){
    document.getElementById('statsTool')?.addEventListener('click',stats);
    document.getElementById('historyTool')?.addEventListener('click',historyPanel);
    document.getElementById('storeTool')?.addEventListener('click',storePanel);
    document.getElementById('budgetTool')?.addEventListener('click',budgetPanel);
    document.getElementById('receiptTool')?.addEventListener('click',receiptPanel);
    document.getElementById('exportCsvTool')?.addEventListener('click',()=>download('grocery.csv',csv(items()),'text/csv'));
    document.getElementById('exportTxtTool')?.addEventListener('click',()=>download('grocery.txt',items().map(i=>`${i.qty}${i.unit?' '+i.unit:''} ${i.name}`).join('\n'),'text/plain'));
    document.getElementById('printTool')?.addEventListener('click',()=>{closePanel();window.print()});
    document.getElementById('voiceTool')?.addEventListener('click',voice);
    document.getElementById('barcodeTool')?.addEventListener('click',barcode);
    document.getElementById('shareTool')?.addEventListener('click',share);
    document.getElementById('notifyTool')?.addEventListener('click',notify);
    document.getElementById('importTool')?.addEventListener('click',importData);
    document.getElementById('customTool')?.addEventListener('click',customize);
  }
  function stats(){const a=items(),b=a.filter(i=>i.bought),spent=b.reduce((s,i)=>s+(+i.price||0)*(+i.qty||1),0),all=a.reduce((s,i)=>s+(+i.price||0)*(+i.qty||1),0);const counts={};a.forEach(i=>counts[i.category]=(counts[i.category]||0)+1);openPanel('📊 Statistics',`<div class="stat-grid"><div><b>${a.length}</b><span>Total items</span></div><div><b>${b.length}</b><span>Purchased</span></div><div><b>${Math.round((b.length/(a.length||1))*100)}%</b><span>Complete</span></div><div><b>${money(spent)}</b><span>Bought value</span></div><div><b>${money(all)}</b><span>Estimated total</span></div><div><b>${Object.keys(counts).length}</b><span>Categories</span></div></div><h3>Most common categories</h3>${Object.entries(counts).sort((x,y)=>y[1]-x[1]).map(([k,v])=>`<p><b>${esc(k)}</b> — ${v}</p>`).join('')||'<p>No data yet.</p>'}`)}
  const money=n=>{const d=read();return new Intl.NumberFormat(undefined,{style:'currency',currency:d.settings?.currency||'USD'}).format(n||0)};
  function historyPanel(){const d=read(),h=Array.isArray(d.history)?d.history:[];openPanel('🗑️ History',`<p>Deleted items are kept here for recovery.</p>${h.length?h.slice(-50).reverse().map((x,i)=>`<div class="history-row"><span>${esc(x.item?.name||'Item')}<small>${new Date(x.at).toLocaleString()}</small></span><button class="small-btn" data-restore="${i}">Restore</button></div>`).join(''):'<p>No deleted items.</p>'}`);document.querySelectorAll('[data-restore]').forEach(b=>b.onclick=()=>{const idx=+b.dataset.restore;const d=read(),h=d.history||[],x=h.slice(-50).reverse()[idx];if(x?.item){d.items=[...(d.items||[]),x.item];d.history=h.filter(y=>y!==x);write(d);closePanel();toast('Item restored')}})}
  function storePanel(){const d=read();d.stores=d.stores||[{id:'default',name:'My Store',aisles:[]}];write(d);openPanel('🏪 Stores',`<input id="storeName" placeholder="New store name"><button class="primary" id="addStore">Add store</button><div>${d.stores.map(s=>`<div class="history-row"><span>🏪 ${esc(s.name)}<small>${(s.aisles||[]).length} aisles</small></span><button class="small-btn" data-store="${s.id}">Edit aisles</button></div>`).join('')}</div>`);document.getElementById('addStore').onclick=()=>{const n=document.getElementById('storeName').value.trim();if(!n)return;d.stores.push({id:uid(),name:n,aisles:[]});write(d);closePanel();storePanel()};document.querySelectorAll('[data-store]').forEach(b=>b.onclick=()=>aisleEditor(b.dataset.store))}
  function aisleEditor(id){const d=read(),s=d.stores.find(x=>x.id===id);openPanel('Aisles — '+esc(s.name),`<input id="aisleText" placeholder="Produce, A1"><button class="primary" id="addAisle">Add aisle</button><div>${(s.aisles||[]).map((a,i)=>`<div class="history-row"><span>${esc(a)}</span><button class="danger" data-delaisle="${i}">Delete</button></div>`).join('')}</div>`);document.getElementById('addAisle').onclick=()=>{const v=document.getElementById('aisleText').value.trim();if(v){s.aisles.push(v);write(d);aisleEditor(id)}};document.querySelectorAll('[data-delaisle]').forEach(b=>b.onclick=()=>{s.aisles.splice(+b.dataset.delaisle,1);write(d);aisleEditor(id)})}
  function budgetPanel(){const d=read(),b=d.settings?.budget||'';openPanel('💰 Budget',`<label>Budget limit<input id="budgetInput" type="number" min="0" step="0.01" value="${b}"></label><button class="primary" id="saveBudget">Save budget</button><div class="budget-card">Estimated: <b>${money(items().reduce((s,i)=>s+(+i.price||0)*(+i.qty||1),0))}</b></div>`);document.getElementById('saveBudget').onclick=()=>{d.settings=d.settings||{};d.settings.budget=+document.getElementById('budgetInput').value||0;write(d);closePanel();toast('Budget saved')}}
  function receiptPanel(){const d=read();d.receipts=d.receipts||[];openPanel('🧾 Receipts',`<label>Final total<input id="receiptTotal" type="number" step="0.01" placeholder="0.00"></label><label>Note<input id="receiptNote" placeholder="Store or trip name"></label><button class="primary" id="saveReceipt">Save receipt</button>${d.receipts.slice().reverse().map(r=>`<div class="history-row"><span>${money(r.total)}<small>${esc(r.note||'Grocery trip')} · ${new Date(r.at).toLocaleDateString()}</small></span></div>`).join('')}`);document.getElementById('saveReceipt').onclick=()=>{d.receipts.push({total:+document.getElementById('receiptTotal').value||0,note:document.getElementById('receiptNote').value,at:Date.now()});write(d);closePanel();toast('Receipt saved')}}
  function csv(a){return ['name,quantity,unit,category,price,brand,bought,notes',...a.map(i=>[i.name,i.qty,i.unit,i.category,i.price,i.brand,i.bought,i.notes].map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(','))].join('\n')}
  function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);toast('Exported '+name)}
  function voice(){if(!('SpeechRecognition'in window||'webkitSpeechRecognition'in window)){toast('Voice input is not supported here');return}const R=window.SpeechRecognition||window.webkitSpeechRecognition,r=new R();r.lang='en-US';r.onresult=e=>{const t=e.results[0][0].transcript;const q=document.getElementById('quickInput');q.value=t;document.getElementById('quickAddBtn').click();closePanel()};r.start();toast('Listening…')}
  async function barcode(){if('BarcodeDetector'in window){try{const formats=await BarcodeDetector.getSupportedFormats();openPanel('▦ Barcode scanner',`<p>Barcode scanning is supported. Camera scanning will use your device when the browser permits it.</p><video id="barcodeVideo" autoplay playsinline></video><button class="primary" id="startScan">Start camera</button><p id="barcodeResult"></p>`);document.getElementById('startScan').onclick=async()=>{const v=document.getElementById('barcodeVideo');const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});v.srcObject=stream;const det=new BarcodeDetector({formats:formats.filter(x=>['ean_13','ean_8','upc_a','upc_e','code_128'].includes(x))});const scan=async()=>{try{const codes=await det.detect(v);if(codes[0]){document.getElementById('barcodeResult').textContent='Found: '+codes[0].rawValue;document.getElementById('quickInput').value=codes[0].rawValue;toast('Barcode captured');stream.getTracks().forEach(t=>t.stop())}else requestAnimationFrame(scan)}catch{requestAnimationFrame(scan)}};scan()}}catch{toast('Barcode scanner unavailable')}}else toast('BarcodeDetector is not supported by this browser')}
  async function share(){const payload=encodeURIComponent(btoa(unescape(encodeURIComponent(JSON.stringify(items())))));const url=location.origin+location.pathname+'#shared='+payload;if(navigator.share){await navigator.share({title:'My Grocery List',url}).catch(()=>{})}else{await navigator.clipboard?.writeText(url);toast('Share link copied')}}
  async function notify(){if(!('Notification'in window)){toast('Notifications are not supported');return}const p=await Notification.requestPermission();if(p==='granted'){new Notification('Grocery Assistant',{body:`You have ${items().filter(i=>!i.bought).length} items left.`});toast('Notifications enabled')}}
  function importData(){openPanel('📥 Import',`<textarea id="importText" rows="8" placeholder="Paste JSON backup or one grocery per line"></textarea><button class="primary" id="doImport">Import</button>`);document.getElementById('doImport').onclick=()=>{const raw=document.getElementById('importText').value.trim();try{const parsed=JSON.parse(raw);if(Array.isArray(parsed.items)){write(parsed);closePanel();toast('Backup imported');return}}catch{}const d=read(),a=items();raw.split(/[\n,]+/).map(x=>x.trim()).filter(Boolean).forEach(n=>a.push({id:uid(),name:n,qty:1,unit:'',category:'Pantry',price:'',brand:'',notes:'',favorite:false,bought:false,created:Date.now()}));d.items=a;write(d);closePanel();toast('Items imported')}}
  function customize(){const d=read();d.settings=d.settings||{};openPanel('🎨 Customize',`<label>Accent color<input id="accent" type="color" value="${d.settings.accent||'#16a34a'}"></label><label class="switch-row"><span>High contrast</span><input id="contrast" type="checkbox" ${d.settings.contrast?'checked':''}></label><label class="switch-row"><span>Compact mode</span><input id="compact" type="checkbox" ${d.settings.compact?'checked':''}></label><label>Default store<input id="defaultStore" value="${esc(d.settings.defaultStore||'')}"></label><button class="primary" id="saveCustom">Save</button>`);document.getElementById('saveCustom').onclick=()=>{d.settings.accent=document.getElementById('accent').value;d.settings.contrast=document.getElementById('contrast').checked;d.settings.compact=document.getElementById('compact').checked;d.settings.defaultStore=document.getElementById('defaultStore').value;write(d);applyCustom();closePanel();toast('Customization saved')}}
  function applyCustom(){const s=read().settings||{};document.documentElement.style.setProperty('--accent',s.accent||'#16a34a');document.documentElement.style.setProperty('--accent2',s.accent||'#15803d');document.body.classList.toggle('high-contrast',!!s.contrast);document.body.classList.toggle('compact',!!s.compact)}
  function enhanceItems(){const list=document.getElementById('listContainer');if(!list)return;list.querySelectorAll('.item').forEach(el=>{if(el.dataset.enhanced)return;el.dataset.enhanced='1';let sx=0,sy=0;el.addEventListener('pointerdown',e=>{sx=e.clientX;sy=e.clientY});el.addEventListener('pointerup',e=>{const dx=e.clientX-sx;if(Math.abs(dx)>90){const id=el.dataset.id;if(dx>0)document.querySelector(`.check[onchange*=\"${id}\"]`)?.click();else document.querySelector(`.mini[onclick*=\"deleteItem('${id}')\"]`)?.click();navigator.vibrate?.(20)}});el.draggable=true;el.addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',el.dataset.id));el.addEventListener('dragover',e=>e.preventDefault());el.addEventListener('drop',e=>{e.preventDefault();const from=e.dataTransfer.getData('text/plain'),a=items(),fi=a.findIndex(x=>x.id===from),ti=a.findIndex(x=>x.id===el.dataset.id);if(fi<0||ti<0)return;const [x]=a.splice(fi,1);a.splice(ti,0,x);a.forEach((x,i)=>x.position=i);saveItems(a);toast('Order updated')})})}
  function addExtraItemFields(){const form=document.getElementById('itemForm');if(!form||document.getElementById('itemSize'))return;const anchor=document.getElementById('itemBrand')?.parentElement;if(!anchor)return;const box=document.createElement('div');box.className='two-col';box.innerHTML='<label>Size<input id="itemSize" maxlength="40" placeholder="e.g. 16 oz"></label><label>Priority<select id="itemPriority"><option value="normal">Normal</option><option value="high">High</option><option value="low">Low</option></select></label>';anchor.insertAdjacentElement('afterend',box);const photo=document.createElement('label');photo.innerHTML='Product photo<input id="itemPhoto" type="file" accept="image/*" capture="environment">';box.insertAdjacentElement('afterend',photo);form.addEventListener('submit',()=>setTimeout(()=>{const d=read(),name=document.getElementById('itemName').value.trim(),matches=(d.items||[]).filter(i=>i.name===name);const x=matches[matches.length-1];if(x){x.size=document.getElementById('itemSize').value;x.priority=document.getElementById('itemPriority').value;const f=document.getElementById('itemPhoto').files?.[0];if(f){const r=new FileReader();r.onload=()=>{x.image=r.result;write(d)};r.readAsDataURL(f)}}write(d)},20));}
  function clearDeletedTracking(){const original=window.deleteItem; if(typeof original!=='function')return;window.deleteItem=(id)=>{const d=read(),x=(d.items||[]).find(i=>i.id===id);if(x){d.history=d.history||[];d.history.push({item:x,at:Date.now()});d.items=d.items.filter(i=>i.id!==id);write(d);toast('Deleted '+x.name+' · tap Undo');document.getElementById('toast').dataset.undo=JSON.stringify(x)}};
  function listenForRender(){const c=document.getElementById('listContainer');if(!c)return;new MutationObserver(()=>enhanceItems()).observe(c,{childList:true,subtree:true});enhanceItems()}
  function addInstall(){let promptEvent=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();promptEvent=e;const s=document.querySelector('.settings-card');if(s&&!document.getElementById('installBtn')){const b=document.createElement('button');b.id='installBtn';b.className='small-btn';b.textContent='📲 Install app';b.onclick=()=>promptEvent.prompt();s.appendChild(b)}})}
  function offline(){const b=document.createElement('div');b.id='offlineBadge';b.className='offline-badge';const up=()=>{b.textContent=navigator.onLine?'🟢 Online':'🔴 Offline';b.classList.toggle('offline',!navigator.onLine)};document.body.appendChild(b);addEventListener('online',up);addEventListener('offline',up);up()}
  function sharedImport(){if(!location.hash.startsWith('#shared='))return;try{const a=JSON.parse(decodeURIComponent(escape(atob(decodeURIComponent(location.hash.slice(8))))));if(Array.isArray(a)&&confirm('Import the shared grocery list?')){saveItems(a);history.replaceState(null,'',location.pathname);toast('Shared list imported')}}catch{}}
  function init(){addToolbar();addExtraItemFields();clearDeletedTracking();listenForRender();addInstall();offline();applyCustom();sharedImport();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
